### ISSUE TITLE
Synchronize jokes

### ISSUE THREAD

**Issue by GPMunk** [floriandj/JokesOnYou#1]
It would be cool if all instances of the application have the same jokes at the same time. 
This way you can laugh about the same joke with others.

**Comment by floriandj** [comment]
Oeps

**Comment by floriandj** [comment]
the idea is to synchronize JokesOnYou applications on the same network. 
So that everyone sees the same jokes.

An extra feature could be sending your 'smiles'/'laughes'/'likes' and everyone who has the application open sees that notification

**Comment by floriandj** [comment]
//1. check network for existing instances
//1.1 create server if no instances exists
//2. connect as a client to the ip adress + port
//3. when the time is there for a joke. emit the joke to each client :)
//4. when the server closes, a client must take over as a server.
